arm_controller:
  type: "position_controllers/JointTrajectoryController"
  joints:
    - yumi_joint_1_l
    - yumi_joint_2_l
    - yumi_joint_3_l
    - yumi_joint_4_l
    - yumi_joint_5_l
    - yumi_joint_6_l
    - yumi_joint_7_l
    - gripper_l_joint
    - yumi_joint_1_r
    - yumi_joint_2_r
    - yumi_joint_3_r
    - yumi_joint_4_r
    - yumi_joint_5_r
    - yumi_joint_6_r
    - yumi_joint_7_r
    - gripper_r_joint
